import type { GalleryConfig } from './index';

export const state = {
  allPosts: [] as any[],
  isEditMode: false,
  sortableInstance: null as any,
  initialOrder: [] as string[],
  filePickerActive: false,
  pendingAction: null as string | null,
  pendingDeletedStackIds: [] as string[],
  pendingDeletedPhotoIds: [] as string[],
  hiddenStatusChanged: false,
  isExpanded: false,
  expandedPhotos: [] as any[],
  expandBtn: null as HTMLElement | null,
  currentEditingWrapper: null as HTMLElement | null,
  currentMiniImages: [] as string[],
  originalMiniImages: '',
  originalMiniCaption: '',
  originalMiniAuthor: '',
  pendingMiniDeleteIdx: null as number | null,
  galleryConfig: null as any,
  importModal: null as HTMLElement | null,
  progressModal: null as HTMLElement | null,
  fileInput: null as HTMLInputElement | null,
  progressBarInner: null as HTMLElement | null,
  progressStatusText: null as HTMLElement | null,
  progressTitle: null as HTMLElement | null,
  refreshPageBtn: null as HTMLElement | null,
  editBtn: null as HTMLElement | null,
  editActions: null as HTMLElement | null,
  saveBtn: null as HTMLElement | null,
  cancelBtn: null as HTMLElement | null,
  addBtn: null as HTMLElement | null,
  galleryBottomBar: null as HTMLElement | null,
  confirmDiscardModal: null as HTMLElement | null,
  confirmDiscardBtn: null as HTMLElement | null,
  cancelDiscardBtn: null as HTMLElement | null,
  confirmDeleteModal: null as HTMLElement | null,
  miniGalleryModal: null as HTMLElement | null,
  closeMiniGalleryBtn: null as HTMLElement | null,
  confirmMiniGalleryBtn: null as HTMLElement | null,
  miniGalleryGrid: null as HTMLElement | null,
  miniCaptionInput: null as HTMLTextAreaElement | null,
  miniAuthorDisplay: null as HTMLElement | null,
  miniImportBtn: null as HTMLElement | null,
  miniFileInput: null as HTMLInputElement | null,
  pendingUploadFiles: [] as { file: File, dataUrl: string }[],
  localSortable: null as any,
  miniSortable: null as any,
};
